# Generated by Django 4.0.4 on 2022-06-09 07:46

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import albums.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
                name='Album',
                fields=[
                    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                    ('title', models.CharField(max_length=30, validators=[
                        django.core.validators.RegexValidator(message='Album title must be alphanumeric',
                                                              regex='^[a-zA-Z0-9 ]+$')])),
                    ('description', models.TextField(blank=True, max_length=255)),
                    ('read_only', models.BooleanField(default=False)),
                    ('allow_anonymous_view', models.BooleanField(default=False)),
                    ('owner',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ],
        ),
        migrations.CreateModel(
                name='Photo',
                fields=[
                    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                    ('image', models.ImageField(upload_to=albums.models.get_upload_path)),
                    ('owner',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ],
        ),
        migrations.CreateModel(
                name='Person',
                fields=[
                    ('person_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                    ('name', models.CharField(max_length=30)),
                    ('owner',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ('photos', models.ManyToManyField(blank=True, to='albums.photo')),
                ],
        ),
        migrations.CreateModel(
                name='Permission',
                fields=[
                    (
                        'id',
                        models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('access', models.IntegerField(choices=[(1, 'Read'), (2, 'Write'), (3, 'Manage')])),
                    ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
                    ('user',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ],
        ),
        migrations.AddField(
                model_name='album',
                name='photos',
                field=models.ManyToManyField(blank=True, to='albums.photo'),
        ),
    ]
