# Generated by Django 4.0.4 on 2022-06-09 07:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
                model_name='album',
                name='id',
                field=models.CharField(default=uuid.uuid4, editable=False, max_length=256, primary_key=True,
                                       serialize=False),
        ),
        migrations.AlterField(
                model_name='photo',
                name='id',
                field=models.CharField(default=uuid.uuid4, editable=False, max_length=256, primary_key=True,
                                       serialize=False),
        ),
    ]
