# Generated by Django 4.0.4 on 2022-06-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0003_person_nameable'),
    ]

    operations = [
        migrations.AlterField(
                model_name='album',
                name='title',
                field=models.CharField(max_length=30),
        ),
    ]
