# Generated by Django 4.0.4 on 2022-06-15 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0004_alter_album_title'),
    ]

    operations = [
        migrations.AddField(
                model_name='person',
                name='thumbnail',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                        related_name='thumbnail', to='albums.photo'),
        ),
    ]
