# Generated by Django 4.0.4 on 2022-06-15 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0006_photo_persons_alter_person_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
                model_name='photo',
                name='persons',
        ),
    ]
